# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

import os
import sys
sys.path.insert(0, os.path.abspath("../src/fora"))

import sphinx_markdown_builder
from sphinx_markdown_builder.markdown_writer import MarkdownTranslator

class GitbookMarkdownTranslator(MarkdownTranslator):
    def visit_Text(self, node):
        text = node.astext().replace("\r\n", "\n")
        text = text.replace("\n", "\n" + "    " * (self.depth.depth - 1))
        if self._escape_text:
            text = self.escape_chars(text)
        self.add(text)

    def depart_Text(self, node):
        pass

    def visit_field_name(self, node):
        _ = (node)
        if ("class" in node.attributes and node.attributes["class"]):
            self.add("##### ")
        else:
            self.add("#### ")

    def depart_field_name(self, node):
        _ = (node)
        self.add("\n")

    def visit_definition(self, node):
        _ = (node)
        self.add("\n")

    def depart_definition(self, node):
        _ = (node)
        pass

    visit_field_body = visit_definition
    depart_field_body = depart_definition

sphinx_markdown_builder.MarkdownBuilder.default_translator_class = GitbookMarkdownTranslator


# -- Project information -----------------------------------------------------

project = 'Fora'
copyright = '2022, oddlama'
author = 'oddlama'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.viewcode",
    "sphinx.ext.napoleon",
    "sphinx_autodoc_typehints",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = []

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'furo'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []


# -- Extension configuration -------------------------------------------------
